name: CI - NestJS Todo App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'npm'

      - name: Instalar dependências
        run: npm ci

      - name: Rodar testes unitários
        run: npm run test

      - name: Rodar testes end-to-end
        run: npm run test:e2e

      - name: Rodar linter
        run: npm run lint

      - name: Compilar o projeto
        run: npm run build
